### PR TITLE
Fix broken formatting in README

### PR DESCRIPTION
**Pull request by miohtama**
### What was wrong?

Had some reST formatting in README that is Markdown

### How was it fixed?

Rewrote as MArkdown

#### Cute Animal Picture

```
Art by Shanaka Dias

           __n__n__
    .------`-\00/-'
   /  ##  ## (oo)
  / \## __   ./
     |//YY \|/
snd  |||   |||

```

### CODE REVIEW

**Comment by miohtama** [comment]
I suspect CI failures are unrelated to README change.

**Comment by carver** [comment]
> I suspect CI failures are unrelated to README change.

Agreed. But since I hate to merge a red test to master, this PR might wait until the dependency issues are resolved.

**Comment by carver** [comment]
Master fixed in #133, awaiting review

**Review by kclowes — APPROVED** [review]
Thanks @miohtama!

**Pull request merged**
