### PR TITLE
[RFR] Python 3.7 support

### LINKED ISSUE #67: Python 3.7 support
Add formal support for python 3.7

- Update `classifiers` in `setup.py`
- Add python3.7 to `tox.ini`
- Add python3.7 run(s) to `.travis.yml`
- Fix any issues or failures that are exposed.

### PR DESCRIPTION
**Pull request by 6ug**
### What I did -
Fixes https://github.com/ethereum/py-trie/issues/67
    

  
### How was it fixed?
- [x] Updated classifiers in setup.py
- [x] Added python3.7 to tox.ini
- [x] Added python3.7 run(s) to .travis.yml
- [x] Fix any issues or failures that are exposed

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by 6ug** [comment]
I can see CI failures are due to some issues with python3.7, need to debug,

**What I am doing** 
I am trying to run tests and debug at that point, I have python3 versions 3.6 and 3.7 installed, so when I try to debug pytest with python3.7 on my fedora machine, it is saying `no module found: pytest` whereas on python3.6 its working like charm.

My machine is in conflict now, I am spinning some containers for testing, this dependency things are so irritating, haha! expect little delay from my side,  working on it.

**Comment by pipermerriam** [comment]
@6ug if you aren't using a virtual environment for your python installs, check this out: https://realpython.com/python-virtual-environments-a-primer/

It'll save you a lot of time.

Also, check out https://github.com/pyenv/pyenv if you are having any trouble installing specific versions of python.

**Comment by 6ug** [comment]
hey @pipermerriam, can you help me to debug errors in python37 failures. I am not able to resolve that error, not getting any hint. I can see that parameterized stuff but everything seem to be okay but suddenly exception coming.

**Comment by pipermerriam** [comment]
Not sure yet.  Investigating.  In the meantime, once https://github.com/ethereum/py-trie/pull/75 is merged you can rebase on that to get rid of the rlp0/1 support.

**Comment by 6ug** [comment]
Re-basing it, right now, thanks! :) :+1:

**Comment by pipermerriam** [comment]
@6ug python3.7 changed some semantics to how generators work.

https://www.python.org/dev/peps/pep-0479/

You can replace all of the lines that `raise StopIteration` with a simple `return` statement.

**Comment by 6ug** [comment]
> @6ug python3.7 changed some semantics to how generators work.
> 
> https://www.python.org/dev/peps/pep-0479/
> 
> You can replace all of the lines that `raise StopIteration` with a simple `return` statement.

Perfect!! updating it, thank you @pipermerriam  :heart:

**Comment by 6ug** [comment]
@pipermerriam  one simple question, so we are going to replace this, for example, 
```
    if node_hash in db:
        node = db[node_hash]
    else:
        raise StopIteration
```
to 
```
    if node_hash in db:
        node = db[node_hash]
    else:
        return
```
but what about other python versions, is it backward compatible!?, let me check by adding commit

**Comment by pipermerriam** [comment]
@6ug yes, try changing, see if CI fails.

**Comment by 6ug** [comment]
and it worked smoothly @pipermerriam, thanks! :) :100: 

they also done following to handle backward compatibility smoothly,
```
def my_generator():
    try:
        ...
        yield next(it)
        ...
    except StopIteration
        return
```
this `PEP 479` was new for me, thanks for pointing me out.

**Review by pipermerriam — APPROVED** [review]

**Comment by pipermerriam** [comment]
Let me know if you want to do anything further, otherwise I'll get this merged.

**Comment by 6ug** [comment]
@pipermerriam nothing remains with respect to python 3.7 supportability I guess, let me know if I wanted to add anything here. :)

**Pull request merged**
