### PR TITLE
Make typing-extensions optional

### PR DESCRIPTION
**Pull request by Uxio0**
- It's not required for Python >= 3.8

### CODE REVIEW

**Review by mmv08 — APPROVED** [review]

**Comment by sunwrobert** [comment]
hi @kclowes , can we please merge this in? Currently running into issues when using `eth-brownie` and installing `gnosis-py` due to the `typing-extensions` dependency.

**Comment by kclowes** [comment]
Thanks for the PR @Uxio0! I changed it to follow the compat pattern from web3, just to be consistent across our libraries. I also added additional lint runs for each Python version we support which feels a little overkill, but I've also run into issues with linting on different Python versions recently. I don't think it adds too much overhead but we can re-evaluate if it feels too clunky or if we want our tests to run faster later.

**Review by fselmo — APPROVED** [review]
@kclowes this lgtm!

**Comment by kclowes** [comment]
@Uxio0 @sunwrobert I'll get this released early next week!

**Comment by kclowes** [comment]
Sorry about the delay, @Uxio0 and @sunwrobert. 2.0.1 is out with this change!

**Pull request merged**
